version: "3.2"
services:

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    networks:
      - mynet
  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - mynet

  backend:    
    restart: always
    build:
      context: ./
    volumes:
      - .:/src
      
    depends_on:
      - mongodb
      - rabbitmq
    environment:
      PORT: 4000
      AMQP_URL: amqp://rabbitmq:5672
      MONGODB: mongodb://mongodb:27017/mydb
      ACCESS_TOKEN_SECRET: kamehameha
    ports:
        - 4000:4000
    networks:
      - mynet

networks:
  mynet:
    driver: bridge      