const swaggerAutogen = require('swagger-autogen')()

const doc = {
    info: {
        version: "1.0.0",
        title: "My API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:3000",
    basePath: "/v1/",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    securityDefinitions: {
        JWT: {
          description: 'Bearer <token>',
          type: 'apiKey',
          in: 'header',
          name: 'Authorization',
        },
      },
    tags: [
        {
            "name": "Posts",
            "description": "Endpoints Posts"
        },{
            "name": "Profile",
            "description": "Endpoints Profile",
        },{
            "name": "Comments",
            "description": "Endpoints Comments"
        },{
            "name": "Feed",
            "description": "Endpoints Feed"
        }
    ],
    definitions: {
        posts: {
            title: "title",
            description: "description"
        },
        comments: {
            description: "description"
        }
    }
}



const outputFile = './swagger_output.json'
const endpointsFiles = ['./app.js']

swaggerAutogen(outputFile, endpointsFiles,doc)